### ISSUE TITLE
Task Sammlung - Dorf

### ISSUE THREAD

**Issue by Studio-VTT-Bastler** [Studio-VTT-Bastler/Studio-VTT-Bastler#11]
## Todos außerhalb von Foundry
- [ ] Dorfkarte (Canvas of Kings)
- [ ] Geschichte des Dorfes (Darin Plothooks dynamisch eingebaut)
- [ ] NSC (Familien, Dynastien)
- [ ] Beschreibung des Dorfes und seiner Örtlichkeiten
- [ ] Beispiele für Verortung und (in Absprache mit dem Weidener Briefspiel) potentiellen Adeligen in deren bereich das dorf liegt
- [ ] Nutzoptionen über Plothub hinaus
- [ ] Plots und Geschichten (+ggf etwas Folklore)
- [ ] potentielle Spielerbases (wenn wir da Karten von machen wollen evtl mit "Anbauoptionen"
## Todos Foundry
- [ ] Modul anlegen
- [ ] Szenen anlegen
- [ ] Journale formatieren
- [ ] Akteure anlegen
